### ISSUE TITLE
When changing the version of Kubernetes, there should be an error if the apiVersion is not supported

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#3542]
When I change the version of Kubernetes, I expect an error  if some apiVersion of a Kind is not supported and a warning if it is deprecated, so I don't have an error when I deploy to the cluster.

- Ideally, it should be possible to fix the problem automatically, but configuration files can change when moving from one version to another.

**Comment by cerebro31** [comment]
For version 1.25, cronjob is no longer [served](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125)
So Monokle Desktop should show a validation error but currently, there are no validation errors regarding Kubernetes Schema for this deprecated API.
![error_version_125](https://user-images.githubusercontent.com/125909758/228179964-b30958ad-3062-461b-b6c3-88f65eb322fd.png)

Here is the manifest for which i tested.
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

**Comment by chargio** [comment]
@olensmar This is a great Wow moment for the valdiation use case. 
We should prioiritize it

**Comment by olensmar** [comment]
Thanks @cerebro1 - indeed we didn't get around to fixing this issue in 2.1 - thanks for bringing it up again though so we can look at it for 2.2!

**Comment by cerebro1** [comment]
Adding a video for reference:

https://github.com/kubeshop/monokle/assets/10183232/2f998871-3300-4cee-81be-0eacca80e37c

**Comment by f1ames** [comment]
Rules for detecting deprecated/removed API versions have been added to validation plugin as a part of [`0.18.0` release](https://github.com/kubeshop/monokle-core/releases/tag/%40monokle%2Fvalidation%400.18.0) (https://github.com/kubeshop/monokle-core/issues/356, https://github.com/kubeshop/monokle-core/issues/372).

**Comment by cerebro31** [comment]
Thank you for the update @f1ames. I will check and update here if there is any issue by end of the day. Thanks!

**Comment by cerebro31** [comment]
@f1ames I can see from the repo that [release](https://github.com/kubeshop/monokle-core/releases/tag/%40monokle%2Fvalidation%400.18.0) of monokle-core has been done but I wanted to understand if Monokle Desktop version 2.2.0 is using it. I tried the same sample code that I have shared above and still can not see any warning or error for `apiVersion: batch/v1beta1`. Am I missing something to enable or add?

**Comment by f1ames** [comment]
@cerebro31 `monokle-core` update is an important part of this issue, but it still needs integration (or at least updating package version) on Monokle Desktop side. So it means it's still not there, probably @olensmar or @chargio can give some insights for which release it is planned.

Thanks for checking this and sorry for a slight confusion.

**Comment by olensmar** [comment]
thanks @f1ames - you're right - we still need to update Monokle Desktop to use the latest core validation library and plugins - this is planned for 2.3 - see https://github.com/kubeshop/monokle/issues/3995

**Comment by devcatalin** [comment]
<img width="795" alt="image" src="https://github.com/kubeshop/monokle/assets/20538711/92d96a0b-5cfc-48d2-a421-89b5d7e02d6d">

We fixed this today, it'll be available soon

**Comment by cerebro31** [comment]
@devcatalin Is this released with v2.2 of Monokle Desktop?

**Comment by cerebro31** [comment]
Sure @devcatalin. That helps. I will check and update in case there is any issue. Thanks for taking this up.

**Comment by cerebro31** [comment]
@devcatalin Could you please help me understand this behaviour of Monokle:
For the fields that have changed with upgraded Kubernetes, Monokle is still not highlighting it.
For example, This is a [sample manifest ](https://github.com/kubevious/mock-data/blob/64356c6a19757126dc96c915e13cc58f163f7f56/cluster-data/large-cluster-mock/k8s/discovery.k8s.io%3AEndpointSlice/gitlab-gitlab-prometheus-server-rrbpq.yaml#L67) where discovery.k8s.io/v1beta1 API version of [EndpointSlice](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#endpointslice-v125) is no longer served as of v1.25.
Changes are: use per Endpoint zone field instead of deprecated topology["topology.kubernetes.io/zone"] field
But if you open this manifest in Monokle, it just gives an error for deprecated API for versions below 1.25 and not for the field zone. Is it the expected behavior?

**Comment by f1ames** [comment]
Hey @cerebro31, let me chip in since I worked on the implementation of those validation rules.

Both depraction (`K8S002`) and removal (`K8S003`) rules are design to detect usage of outdated value for `apiVersion` field. So what you described:

> But if you open this manifest in Monokle, it just gives an error for deprecated API for versions below 1.25 and not for the field zone.

is an expected behavior.

---

Now, the schema itself (so all the fields and their values) is validated by `K8S001` rule, which is designed to detect if used fields matches resource expected schema and if those fields have expected value types.

So when you have `discovery.k8s.io/v1beta1` API version, the file will be validated based on schema for this version (where `topology` is a valid field). And when you update it to `discovery.k8s.io/v1` API version, it will be validated based on newer schema which doesn't have this field (it uses `deprecatedTopology`).

So AFAIU, `topology` field should be highlighted after changing `apiVersion` to `discovery.k8s.io/v1`. But... I see it's not - so this seems like an issue in fact but not related to deprecation rules, but more to `K8S001` rule. @WitoDelnat @devcatalin is it correct assumption on how it should work or am I missing something?

**Comment by olensmar** [comment]
@cerebro1 @f1ames this might be because (afaik) k8s schemas are generally not "exclusive" - i.e. they don't prohibit properties that are not defined, so in your case the fact that you have an "old" `topology` property in your resource doesn't actually violate the schema itself. What could be a schema violation though is if the `deprecatedTopology` field is required in the new schema (which I don't know if it is) - in which case you should get an error about a missing required property.

**Comment by WitoDelnat** [comment]
My two cents on improving this:

- A configurable [strict mode](https://github.com/kubeshop/monokle-saas/issues/831) can be considered to further tighten validation. This might lead to many false positives.
- The deprecation rule gets improved to also be field-aware instead of solely API kind aware. Finding these fields is manual work and time consuming.

**Comment by olensmar** [comment]
"strict-mode" sounds like a good setting to have for the schema validator
